-- 002_create_tables.sql
-- Vietnamese schema tables for PlotFarm
-- Note: This is a placeholder implementation covering core tables.

-- 1. Roles table (VAITRO)
CREATE TABLE dbo.VAITRO (
    MaVaiTro VARCHAR(20) NOT NULL PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL,
    MoTa NVARCHAR(255) NULL
);

-- 2. Customers (KHACHHANG)
CREATE TABLE dbo.KHACHHANG (
    MaKH VARCHAR(20) NOT NULL PRIMARY KEY,
    TenKH NVARCHAR(255) NOT NULL,
    Email VARCHAR(254) NOT NULL UNIQUE,
    DienThoai VARCHAR(15) NOT NULL,
    DiaChi NVARCHAR(500) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'ACTIVE', N'INACTIVE')),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

-- 3. Employees (NHANVIEN)
CREATE TABLE dbo.NHANVIEN (
    MaNV VARCHAR(20) NOT NULL PRIMARY KEY,
    Ho NVARCHAR(100) NOT NULL,
    Ten NVARCHAR(100) NOT NULL,
    Email VARCHAR(254) NOT NULL UNIQUE,
    DienThoai VARCHAR(15) NOT NULL,
    ChucVu VARCHAR(50) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'ACTIVE', N'INACTIVE')),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

-- 4. Accounts (TAIKHOAN)
CREATE TABLE dbo.TAIKHOAN (
    TenDangNhap VARCHAR(50) NOT NULL PRIMARY KEY,
    MatKhauHash VARCHAR(255) NOT NULL,
    MaVaiTro VARCHAR(20) NOT NULL,
    MaKH VARCHAR(20) NULL,
    MaNV VARCHAR(20) NULL,
    CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (MaVaiTro) REFERENCES dbo.VAITRO(MaVaiTro),
    CONSTRAINT FK_TAIKHOAN_KHACHHANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH),
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHANVIEN(MaNV),
    CONSTRAINT CK_TAIKHOAN_KHACHHANG_NV CHECK (
        (MaKH IS NULL AND MaNV IS NOT NULL) OR
        (MaKH IS NOT NULL AND MaNV IS NULL)
    )
);

-- 5. Farm (NONGTRAI)
CREATE TABLE dbo.NONGTRAI (
    MaNongTrai VARCHAR(20) NOT NULL PRIMARY KEY,
    TenNongTrai NVARCHAR(255) NOT NULL,
    MaChuNongTrai VARCHAR(20) NOT NULL,
    DiaChi NVARCHAR(500) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'PENDING', N'APPROVED', N'REJECTED')),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_NONGTRAI_CHUNONGTRAIVAI_TRO FOREIGN KEY (MaChuNongTrai) REFERENCES dbo.NHANVIEN(MaNV)
);

-- Additional tables (ODAT, HOPDONGTHUE, CAYTRONG, DOTCANHTAC, NHATKYCANHTAC, LOAICHAMSOC, YEUCAUCHAMSOC, CAMERAODAT, THUHOACH, GIAOHANG, THANHTOAN, THONGBAO, ...) should be added following the same pattern with appropriate PK/FK/UNIQUE/CHECK constraints.

-- End of script
