-- 002_create_tables.sql
-- Vietnamese schema tables for PlotFarm
-- Idempotent table creation script

-- 1. Roles table (VAITRO)
IF OBJECT_ID(N'dbo.VAITRO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VAITRO (
        MaVaiTro VARCHAR(20) NOT NULL PRIMARY KEY,
        TenVaiTro VARCHAR(50) NOT NULL,
        MoTa NVARCHAR(255) NULL
    );
END;

-- 2. Customers (KHACHHANG)
IF OBJECT_ID(N'dbo.KHACHHANG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.KHACHHANG (
        MaKH VARCHAR(20) NOT NULL PRIMARY KEY,
        TenKH NVARCHAR(255) NOT NULL,
        Email VARCHAR(254) NOT NULL UNIQUE,
        DienThoai VARCHAR(15) NOT NULL,
        DiaChi NVARCHAR(500) NOT NULL,
        TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'ACTIVE', N'INACTIVE')),
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL
    );
END;

-- 3. Employees (NHANVIEN)
IF OBJECT_ID(N'dbo.NHANVIEN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.NHANVIEN (
        MaNV VARCHAR(20) NOT NULL PRIMARY KEY,
        Ho NVARCHAR(100) NOT NULL,
        Ten NVARCHAR(100) NOT NULL,
        Email VARCHAR(254) NOT NULL UNIQUE,
        DienThoai VARCHAR(15) NOT NULL,
        ChucVu VARCHAR(50) NOT NULL,
        TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'ACTIVE', N'INACTIVE')),
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL
    );
END;

-- 4. Accounts (TAIKHOAN)
IF OBJECT_ID(N'dbo.TAIKHOAN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TAIKHOAN (
        TenDangNhap VARCHAR(50) NOT NULL PRIMARY KEY,
        MatKhauHash VARCHAR(255) NOT NULL,
        MaVaiTro VARCHAR(20) NOT NULL,
        MaKH VARCHAR(20) NULL,
        MaNV VARCHAR(20) NULL,
        CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (MaVaiTro) REFERENCES dbo.VAITRO(MaVaiTro),
        CONSTRAINT FK_TAIKHOAN_KHACHHANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH),
        CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHANVIEN(MaNV),
        CONSTRAINT CK_TAIKHOAN_KHACHHANG_NV CHECK (
            (MaKH IS NULL AND MaNV IS NOT NULL) OR
            (MaKH IS NOT NULL AND MaNV IS NULL)
        )
    );
END;

-- 5. Farm (NONGTRAI)
IF OBJECT_ID(N'dbo.NONGTRAI', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.NONGTRAI (
        MaNongTrai VARCHAR(20) NOT NULL PRIMARY KEY,
        TenNongTrai NVARCHAR(255) NOT NULL,
        MaChuNongTrai VARCHAR(20) NOT NULL,
        DiaChi NVARCHAR(500) NOT NULL,
        TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'PENDING', N'APPROVED', N'REJECTED')),
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL,
        CONSTRAINT FK_NONGTRAI_CHUNONGTRAIVAI_TRO FOREIGN KEY (MaChuNongTrai) REFERENCES dbo.NHANVIEN(MaNV)
    );
END;

-- 6. Cây Trồng (CAYTRONG)
IF OBJECT_ID(N'dbo.CAYTRONG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CAYTRONG (
        MaCayTrong VARCHAR(20) NOT NULL PRIMARY KEY,
        TenCayTrong NVARCHAR(255) NOT NULL,
        LoaiCay NVARCHAR(100) NOT NULL,
        ThoiGianThuHoach INT NOT NULL, -- Tính bằng ngày
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL
    );
END;

-- 7. Ô Đất (ODAT)
IF OBJECT_ID(N'dbo.ODAT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ODAT (
        MaODat VARCHAR(20) NOT NULL PRIMARY KEY,
        MaNongTrai VARCHAR(20) NOT NULL,
        TenODat NVARCHAR(100) NOT NULL,
        DienTich DECIMAL(10,2) NOT NULL,
        TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'TRONG', N'DANG_THUE', N'BAO_TRI')),
        GiaThue DECIMAL(18,0) NOT NULL, -- Giá thuê 1 tháng
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL,
        CONSTRAINT FK_ODAT_NONGTRAI FOREIGN KEY (MaNongTrai) REFERENCES dbo.NONGTRAI(MaNongTrai)
    );
END;

-- 8. Hợp Đồng Thuê (HOPDONGTHUE)
IF OBJECT_ID(N'dbo.HOPDONGTHUE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HOPDONGTHUE (
        MaHopDong VARCHAR(20) NOT NULL PRIMARY KEY,
        MaKH VARCHAR(20) NOT NULL,
        MaODat VARCHAR(20) NOT NULL,
        MaCayTrong VARCHAR(20) NOT NULL,
        NgayBatDau DATE NOT NULL,
        NgayKetThuc DATE NOT NULL,
        TongTien DECIMAL(18,0) NOT NULL,
        TrangThai VARCHAR(20) NOT NULL CHECK (TrangThai IN (N'ACTIVE', N'COMPLETED', N'CANCELLED')),
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt DATETIME2 NULL,
        CONSTRAINT FK_HOPDONG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH),
        CONSTRAINT FK_HOPDONG_ODAT FOREIGN KEY (MaODat) REFERENCES dbo.ODAT(MaODat),
        CONSTRAINT FK_HOPDONG_CAYTRONG FOREIGN KEY (MaCayTrong) REFERENCES dbo.CAYTRONG(MaCayTrong)
    );
END;
