import type {
  CareRequestItem,
  FarmerPlotItem,
  FarmerProfileData,
  FarmingLogItem,
  HarvestItem,
} from "./farmer.types";

export const MOCK_FARMER_PROFILES: Record<string, FarmerProfileData> = {
  NV0001: {
    id: "NV0001",
    username: "farmer",
    name: "Lê Văn Canh Tác",
    email: "farmer@plotfarm.com",
    phone: "0912 345 678",
    assignedFarms: [
      "Nông trại Thung Lũng Xanh (Lâm Đồng)",
      "Trang trại Đồi Chè & Cây Ăn Quả (Bảo Lộc)",
    ],
    assignedPlotCount: 5,
    bio: "Hơn 12 năm kinh nghiệm canh tác lúa đặc sản hữu cơ và rau quả nhà kính công nghệ cao tiêu chuẩn VietGAP/GlobalGAP.",
    joinedDate: "10/01/2023",
    specialties: ["Lúa chất lượng cao", "Rau quả nhà màng", "Hệ thống tưới nhỏ giọt Israel", "Ủ phân vi sinh"],
    roleTitle: "Kỹ sư Canh tác Cấp cao (Lâm Đồng)",
    avatarIcon: "👨‍🌾",
  },
  NV0002: {
    id: "NV0002",
    username: "farmer2",
    name: "Nguyễn Thị Đồng Ruộng",
    email: "farmer2@plotfarm.com",
    phone: "0988 765 432",
    assignedFarms: ["Nông trại Hữu Cơ Củ Chi (TP.HCM)"],
    assignedPlotCount: 3,
    bio: "Chuyên gia nông nghiệp hữu cơ vi sinh, 8 năm kinh nghiệm luân canh rau màu ngắn ngày và kiểm soát sâu bệnh sinh học.",
    joinedDate: "15/06/2024",
    specialties: ["Rau ăn lá thủy canh", "Phân trùn quế", "Bảo quản rau tươi đóng gói", "Kiểm nghiệm vi sinh"],
    roleTitle: "Chuyên viên Nông nghiệp Hữu cơ (Củ Chi)",
    avatarIcon: "👩‍🌾",
  },
  NV0003: {
    id: "NV0003",
    username: "farmer3",
    name: "Trần Văn Vườn",
    email: "farmer3@plotfarm.com",
    phone: "0903 112 233",
    assignedFarms: ["Khu Nông Nghiệp Công Nghệ Cao Mê Kông (Tiền Giang)"],
    assignedPlotCount: 2,
    bio: "Chuyên gia cây ăn trái nhiệt đới xuất khẩu (Xoài Cát Hòa Lộc, Bưởi Da Xanh), ứng dụng cảm biến IoT đo độ ẩm tầng rễ sâu.",
    joinedDate: "01/03/2025",
    specialties: ["Cây ăn trái đặc sản", "Kỹ thuật bao trái chống ruồi vàng", "Xử lý ra hoa trái vụ", "IoT đồng bằng"],
    roleTitle: "Kỹ thuật viên Vườn cây Ăn trái (Mê Kông)",
    avatarIcon: "🧑‍🌾",
  },
};

export const INITIAL_FARMER_PROFILE = MOCK_FARMER_PROFILES.NV0001;

export const INITIAL_FARMER_PLOTS: FarmerPlotItem[] = [
  // --- Farmer 1 (NV0001 - Lê Văn Canh Tác) ---
  {
    id: "plot-1",
    assignedFarmerId: "NV0001",
    farmName: "Nông trại Thung Lũng Xanh (Lâm Đồng)",
    plotCode: "#PL-0192",
    plotStatus: "IN_USE",
    customerName: "Nguyễn Văn Nông",
    contractId: "#HD-2026-001",
    plantCrop: "Lúa ST25 Đặc sản",
    startDate: "15/01/2026",
    endDate: "15/05/2026",
    plantStatus: "Đang ra hoa",
    progress: 75,
    lastUpdate: "Hôm nay 08:30",
    areaSquareMeter: 5000,
  },
  {
    id: "plot-2",
    assignedFarmerId: "NV0001",
    farmName: "Nông trại Thung Lũng Xanh (Lâm Đồng)",
    plotCode: "#PL-0205",
    plotStatus: "IN_USE",
    customerName: "Trần Thị Mai",
    contractId: "#HD-2026-009",
    plantCrop: "Cà chua bi hữu cơ",
    startDate: "01/02/2026",
    endDate: "30/06/2026",
    plantStatus: "Phát triển tốt",
    progress: 55,
    lastUpdate: "Hôm qua 16:45",
    areaSquareMeter: 2500,
  },
  {
    id: "plot-3",
    assignedFarmerId: "NV0001",
    farmName: "Trang trại Đồi Chè & Cây Ăn Quả (Bảo Lộc)",
    plotCode: "#PL-0311",
    plotStatus: "IN_USE",
    customerName: "Hoàng Minh Tuấn",
    contractId: "#HD-2026-015",
    plantCrop: "Dưa lưới Nhật Ichiba",
    startDate: "10/12/2025",
    endDate: "15/03/2026",
    plantStatus: "Chuẩn bị thu hoạch",
    progress: 92,
    lastUpdate: "Hôm nay 07:15",
    areaSquareMeter: 3000,
  },
  {
    id: "plot-4",
    assignedFarmerId: "NV0001",
    farmName: "Trang trại Đồi Chè & Cây Ăn Quả (Bảo Lộc)",
    plotCode: "#PL-0402",
    plotStatus: "ACTIVE",
    customerName: "Phạm Quốc Dũng",
    contractId: "#HD-2026-022",
    plantCrop: "Cải bẹ xanh thủy canh",
    startDate: "20/02/2026",
    endDate: "20/04/2026",
    plantStatus: "Đang gieo trồng",
    progress: 20,
    lastUpdate: "2 ngày trước",
    areaSquareMeter: 1200,
  },
  {
    id: "plot-5",
    assignedFarmerId: "NV0001",
    farmName: "Nông trại Thung Lũng Xanh (Lâm Đồng)",
    plotCode: "#PL-0108",
    plotStatus: "RESTING",
    customerName: "Đất đang cải tạo vi sinh",
    contractId: "--",
    plantCrop: "Cải tạo đất hữu cơ",
    startDate: "01/03/2026",
    endDate: "01/04/2026",
    plantStatus: "Cần chú ý chăm sóc",
    progress: 10,
    lastUpdate: "3 ngày trước",
    areaSquareMeter: 4000,
  },

  // --- Farmer 2 (NV0002 - Nguyễn Thị Đồng Ruộng - Củ Chi) ---
  {
    id: "plot-6",
    assignedFarmerId: "NV0002",
    farmName: "Nông trại Hữu Cơ Củ Chi (TP.HCM)",
    plotCode: "#PL-0501",
    plotStatus: "IN_USE",
    customerName: "Đặng Thu Thảo",
    contractId: "#HD-2026-031",
    plantCrop: "Rau muống hữu cơ cao sản",
    startDate: "18/02/2026",
    endDate: "25/03/2026",
    plantStatus: "Phát triển tốt",
    progress: 65,
    lastUpdate: "Hôm nay 09:10",
    areaSquareMeter: 1500,
  },
  {
    id: "plot-7",
    assignedFarmerId: "NV0002",
    farmName: "Nông trại Hữu Cơ Củ Chi (TP.HCM)",
    plotCode: "#PL-0502",
    plotStatus: "IN_USE",
    customerName: "Vũ Đình Khang",
    contractId: "#HD-2026-034",
    plantCrop: "Rau dền đỏ & Mồng tơi",
    startDate: "22/02/2026",
    endDate: "30/03/2026",
    plantStatus: "Phát triển tốt",
    progress: 50,
    lastUpdate: "Hôm qua 15:20",
    areaSquareMeter: 1800,
  },
  {
    id: "plot-8",
    assignedFarmerId: "NV0002",
    farmName: "Nông trại Hữu Cơ Củ Chi (TP.HCM)",
    plotCode: "#PL-0503",
    plotStatus: "ACTIVE",
    customerName: "Ngô Mỹ Linh",
    contractId: "#HD-2026-039",
    plantCrop: "Giàn mướp hương & Bầu sao",
    startDate: "05/02/2026",
    endDate: "10/05/2026",
    plantStatus: "Đang ra hoa",
    progress: 45,
    lastUpdate: "Hôm nay 11:00",
    areaSquareMeter: 2200,
  },

  // --- Farmer 3 (NV0003 - Trần Văn Vườn - Tiền Giang) ---
  {
    id: "plot-9",
    assignedFarmerId: "NV0003",
    farmName: "Khu Nông Nghiệp Công Nghệ Cao Mê Kông (Tiền Giang)",
    plotCode: "#PL-0601",
    plotStatus: "IN_USE",
    customerName: "Lê Hoàng Phúc",
    contractId: "#HD-2026-042",
    plantCrop: "Xoài Cát Hòa Lộc bao trái",
    startDate: "01/11/2025",
    endDate: "20/04/2026",
    plantStatus: "Chuẩn bị thu hoạch",
    progress: 88,
    lastUpdate: "Hôm nay 06:45",
    areaSquareMeter: 8000,
  },
  {
    id: "plot-10",
    assignedFarmerId: "NV0003",
    farmName: "Khu Nông Nghiệp Công Nghệ Cao Mê Kông (Tiền Giang)",
    plotCode: "#PL-0602",
    plotStatus: "IN_USE",
    customerName: "Trương Gia Huy",
    contractId: "#HD-2026-048",
    plantCrop: "Bưởi Da Xanh ruột hồng",
    startDate: "15/10/2025",
    endDate: "30/05/2026",
    plantStatus: "Phát triển tốt",
    progress: 70,
    lastUpdate: "Hôm qua 17:30",
    areaSquareMeter: 10000,
  },
];

export const INITIAL_FARMING_LOGS: FarmingLogItem[] = [
  // Logs for Farmer 1
  {
    id: "log-1",
    plot: "#PL-0192",
    date: "10/03/2026",
    activity: "Bón phân",
    plantStatus: "Đang trổ bông đều, thân cứng",
    description: "Bón phân Kali & Vi lượng đợt 3 hỗ trợ chắc hạt lúa ST25. Kiểm tra hệ thống nước tưới rãnh tiêu chuẩn 5cm.",
    imageEvidence: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&auto=format&fit=crop&q=80",
    createdBy: "Lê Văn Canh Tác (Nông Dân)",
  },
  {
    id: "log-2",
    plot: "#PL-0205",
    date: "09/03/2026",
    activity: "Tỉa cành",
    plantStatus: "Chùm quả đầu phát triển nhanh, không nấm",
    description: "Cắt tỉa lá già sát gốc, cố định thân cà chua bi vào dây leo nhà kính. Phun men vi sinh phòng bệnh nấm phấn trắng.",
    imageEvidence: "https://images.unsplash.com/photo-1592417817098-8f3d69106093?w=400&auto=format&fit=crop&q=80",
    createdBy: "Lê Văn Canh Tác (Nông Dân)",
  },
  {
    id: "log-3",
    plot: "#PL-0311",
    date: "08/03/2026",
    activity: "Kiểm tra sâu bệnh",
    plantStatus: "Độ ngọt Brix 14.5, vỏ lưới sắc nét",
    description: "Đo nồng độ đường dưa lưới Ichiba bằng khúc xạ kế. Giảm tưới nước 30% để chuẩn bị thu hoạch trong 5 ngày tới.",
    imageEvidence: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&auto=format&fit=crop&q=80",
    createdBy: "Lê Văn Canh Tác (Nông Dân)",
  },
  {
    id: "log-4",
    plot: "#PL-0192",
    date: "05/03/2026",
    activity: "Tưới nước",
    plantStatus: "Độ ẩm đất đạt 70%",
    description: "Bơm xả ngập nước điều tiết nhiệt độ đồng ruộng chống nắng nóng đợt gió Tây.",
    imageEvidence: "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=400&auto=format&fit=crop&q=80",
    createdBy: "Lê Văn Canh Tác (Nông Dân)",
  },

  // Logs for Farmer 2 (Củ Chi)
  {
    id: "log-5",
    plot: "#PL-0501",
    date: "10/03/2026",
    activity: "Bón phân",
    plantStatus: "Rau muống xanh mướt, đọt non",
    description: "Tưới bổ sung dịch đạm trùn quế pha loãng tỷ lệ 1:20. Kiểm tra đất đạt độ ẩm 75%.",
    imageEvidence: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80",
    createdBy: "Nguyễn Thị Đồng Ruộng (Nông Dân)",
  },
  {
    id: "log-6",
    plot: "#PL-0502",
    date: "08/03/2026",
    activity: "Làm cỏ",
    plantStatus: "Dền đỏ lên đồng đều",
    description: "Làm cỏ tay dọc luống rau dền và mồng tơi, phủ thêm lớp trấu hun giữ ẩm gốc.",
    imageEvidence: "https://images.unsplash.com/photo-1592417817098-8f3d69106093?w=400&auto=format&fit=crop&q=80",
    createdBy: "Nguyễn Thị Đồng Ruộng (Nông Dân)",
  },

  // Logs for Farmer 3 (Mê Kông)
  {
    id: "log-7",
    plot: "#PL-0601",
    date: "09/03/2026",
    activity: "Tỉa cành",
    plantStatus: "Trái xoài cát da căng bóng",
    description: "Tỉa bớt các cành tăm che khuất ánh sáng, kiểm tra túi bao trái chuyên dụng tránh ruồi đục quả.",
    imageEvidence: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&auto=format&fit=crop&q=80",
    createdBy: "Trần Văn Vườn (Nông Dân)",
  },
];

export const INITIAL_CARE_REQUESTS: CareRequestItem[] = [
  // Requests for Farmer 1
  {
    id: "REQ-101",
    plot: "#PL-0192",
    customer: "Nguyễn Văn Nông",
    requestType: "Chụp ảnh tiến độ",
    description: "Nhờ bác nông dân chụp ảnh bông lúa trổ đợt này và đo giúp chiều cao cây lúa xem có đạt chuẩn không.",
    createdDate: "09/03/2026 14:20",
    status: "PENDING",
    farmerNote: "",
    evidenceImage: "",
    processedDate: "",
  },
  {
    id: "REQ-102",
    plot: "#PL-0205",
    customer: "Trần Thị Mai",
    requestType: "Tưới thêm nước",
    description: "Tôi thấy camera cảm biến báo độ ẩm đất 55%, phiền bác tăng cường tưới nhỏ giọt thêm 15 phút buổi chiều.",
    createdDate: "09/03/2026 09:00",
    status: "IN_PROGRESS",
    farmerNote: "Đã bật van hẹn giờ tưới nhỏ giọt lúc 16h30, độ ẩm đã tăng lên 68%.",
    evidenceImage: "https://images.unsplash.com/photo-1592417817098-8f3d69106093?w=400&auto=format&fit=crop&q=80",
    processedDate: "09/03/2026 17:00",
  },
  {
    id: "REQ-103",
    plot: "#PL-0311",
    customer: "Hoàng Minh Tuấn",
    requestType: "Kiểm tra sâu bệnh",
    description: "Kiểm tra mặt dưới lá xem có bọ trĩ hoặc rệp sáp trắng không, đợt trước vườn bên cạnh có bị lây.",
    createdDate: "07/03/2026 11:30",
    status: "COMPLETED",
    farmerNote: "Đã rà soát toàn bộ luống dưa lưới, cây sạch bọ rệp, lá bóng khỏe. Đã xịt bổ sung chế phẩm neem oil thảo mộc.",
    evidenceImage: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&auto=format&fit=crop&q=80",
    processedDate: "07/03/2026 15:45",
  },
  {
    id: "REQ-104",
    plot: "#PL-0402",
    customer: "Phạm Quốc Dũng",
    requestType: "Bón phân bổ sung",
    description: "Muốn bổ sung thêm đạm cá hữu cơ lên men cho luống rau cải bẹ xanh.",
    createdDate: "06/03/2026 08:15",
    status: "CANNOT_RESOLVE",
    farmerNote: "Rau mới gieo được 8 ngày rễ còn non, bón đạm cá lúc này dễ gây xót rễ. Đã tư vấn khách lùi lại 10 ngày nữa.",
    evidenceImage: "",
    processedDate: "06/03/2026 10:30",
  },

  // Requests for Farmer 2 (Củ Chi)
  {
    id: "REQ-201",
    plot: "#PL-0501",
    customer: "Đặng Thu Thảo",
    requestType: "Thu hoạch sớm",
    description: "Nhà cuối tuần có tiệc, nhờ bác thu hoạch trước 5kg rau muống ngon nhất chuyển vào sáng thứ Bảy.",
    createdDate: "09/03/2026 10:00",
    status: "PENDING",
    farmerNote: "",
    evidenceImage: "",
    processedDate: "",
  },
  {
    id: "REQ-202",
    plot: "#PL-0502",
    customer: "Vũ Đình Khang",
    requestType: "Kiểm tra sâu bệnh",
    description: "Lá dền có vài lỗ thủng nhỏ, nhờ cô kiểm tra xem có sâu xanh ăn lá không.",
    createdDate: "08/03/2026 16:00",
    status: "COMPLETED",
    farmerNote: "Đã bắt sâu bướm thủ công và xịt nước tỏi ớt xua đuổi, không dùng hóa chất.",
    evidenceImage: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80",
    processedDate: "09/03/2026 08:30",
  },

  // Requests for Farmer 3 (Mê Kông)
  {
    id: "REQ-301",
    plot: "#PL-0601",
    customer: "Lê Hoàng Phúc",
    requestType: "Gửi ảnh trái cây",
    description: "Nhờ kỹ sư chụp ảnh chùm xoài cát chuẩn bị thu hoạch để đăng quà tặng đối tác.",
    createdDate: "08/03/2026 14:00",
    status: "PENDING",
    farmerNote: "",
    evidenceImage: "",
    processedDate: "",
  },
];

export const INITIAL_HARVESTS: HarvestItem[] = [
  // Harvests for Farmer 1
  {
    id: "HV-0089",
    plot: "#PL-0311",
    customer: "Hoàng Minh Tuấn",
    plantCrop: "Dưa lưới Nhật Ichiba",
    expectedHarvestDate: "15/03/2026",
    actualHarvestDate: "15/03/2026",
    expectedQuantity: "450 kg",
    actualQuantity: "475 kg",
    harvestStatus: "SCHEDULED",
    note: "Trái đều đẹp từ 1.5 - 1.8 kg/quả, độ ngọt cao, chuẩn bị đóng giỏ carton có lót xốp lưới.",
    packageStatus: "NOT_PACKED",
    deliveryStatus: "WAITING_PICKUP",
  },
  {
    id: "HV-0090",
    plot: "#PL-0192",
    customer: "Nguyễn Văn Nông",
    plantCrop: "Lúa ST25 Đặc sản",
    expectedHarvestDate: "15/05/2026",
    actualHarvestDate: "",
    expectedQuantity: "2.800 kg",
    actualQuantity: "",
    harvestStatus: "SCHEDULED",
    note: "Dự kiến thu hoạch bằng máy gặt đập liên hợp cụm Thung Lũng Xanh.",
    packageStatus: "NOT_PACKED",
    deliveryStatus: "WAITING_PICKUP",
  },
  {
    id: "HV-0081",
    plot: "#PL-0205",
    customer: "Trần Thị Mai",
    plantCrop: "Cà chua bi hữu cơ đợt 1",
    expectedHarvestDate: "28/02/2026",
    actualHarvestDate: "28/02/2026",
    expectedQuantity: "120 kg",
    actualQuantity: "135 kg",
    harvestStatus: "HARVESTED",
    note: "Chín đỏ đều, đóng hộp xốp thông hơi 500g, đã giao thành công tận nhà khách hàng.",
    packageStatus: "PACKED",
    deliveryStatus: "DELIVERED",
  },

  // Harvests for Farmer 2 (Củ Chi)
  {
    id: "HV-0095",
    plot: "#PL-0501",
    customer: "Đặng Thu Thảo",
    plantCrop: "Rau muống hữu cơ",
    expectedHarvestDate: "25/03/2026",
    actualHarvestDate: "",
    expectedQuantity: "300 kg",
    actualQuantity: "",
    harvestStatus: "SCHEDULED",
    note: "Dự kiến cắt sáng sớm, đóng túi kraft thoáng khí 1kg.",
    packageStatus: "NOT_PACKED",
    deliveryStatus: "WAITING_PICKUP",
  },
  {
    id: "HV-0096",
    plot: "#PL-0502",
    customer: "Vũ Đình Khang",
    plantCrop: "Rau dền đỏ hữu cơ đợt 1",
    expectedHarvestDate: "01/03/2026",
    actualHarvestDate: "01/03/2026",
    expectedQuantity: "150 kg",
    actualQuantity: "162 kg",
    harvestStatus: "HARVESTED",
    note: "Rau tươi không dập nát, giao lạnh trong ngày.",
    packageStatus: "PACKED",
    deliveryStatus: "DELIVERED",
  },

  // Harvests for Farmer 3 (Mê Kông)
  {
    id: "HV-0098",
    plot: "#PL-0601",
    customer: "Lê Hoàng Phúc",
    plantCrop: "Xoài Cát Hòa Lộc vụ Xuân",
    expectedHarvestDate: "20/04/2026",
    actualHarvestDate: "",
    expectedQuantity: "1.200 kg",
    actualQuantity: "",
    harvestStatus: "SCHEDULED",
    note: "Dán tem truy xuất nguồn gốc QR code từng trái, đóng thùng carton xuất khẩu 5kg.",
    packageStatus: "STORAGE_COOL",
    deliveryStatus: "WAITING_PICKUP",
  },
];
